[package]
name = "gear-lib-sr25519"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
schnorrkel = { version = "0.10.2", default-features = false, features = ["preaudit_deprecated", "u64_backend"] }
