[package]
name = "gear-lib-derive"
version = "0.3.2"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
gear-lib-macros = { path = "macros" }
