name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Artifact cache
        uses: Swatinem/rust-cache@v1

      - name: Pin toolchain
        run: make init

      - name: Check fmt
        run: make fmt-check

      - name: Run linter
        run: make linter

      - name: Build
        run: make build

      - name: Run tests
        run: make test
